export const defaultMasterData = {
  units: [
    { name: "Pendaftaran", code: "PDF", description: "Loket dan front office pendaftaran pasien." },
    { name: "Farmasi", code: "FRM", description: "Operasional farmasi dan gudang obat." },
    { name: "Kasir", code: "KSR", description: "Pembayaran dan administrasi transaksi." },
    { name: "Laboratorium", code: "LAB", description: "Unit pemeriksaan laboratorium." },
    { name: "Radiologi", code: "RAD", description: "Unit radiologi dan perangkat viewer." },
    { name: "Poli Anak", code: "PAN", description: "Area layanan poli anak." },
    { name: "Rawat Inap", code: "RIN", description: "Area perawatan inap dan nurse station." },
    { name: "IT", code: "IT", description: "Divisi IT Support dan ruang server." },
    { name: "IGD", code: "IGD", description: "Instalasi gawat darurat." },
    { name: "Rawat Jalan", code: "RJ", description: "Area layanan rawat jalan." },
    { name: "Administrasi", code: "ADM", description: "Administrasi umum rumah sakit." },
    { name: "Keuangan", code: "KEU", description: "Keuangan, akuntansi, dan klaim." },
    { name: "HRD", code: "HRD", description: "Pengelolaan SDM internal." },
    { name: "Gudang Umum", code: "GUD", description: "Penyimpanan logistik non-klinis." },
    { name: "Manajemen", code: "MGT", description: "Ruang kerja manajemen." },
    { name: "Ruang Operasi", code: "OK", description: "Area operasional ruang operasi." }
  ],
  rooms: [
    { unitCode: "PDF", name: "Front Office", code: "FO", description: "Area meja informasi pendaftaran." },
    { unitCode: "PDF", name: "Loket Pendaftaran", code: "LP", description: "Area input dan verifikasi pendaftaran." },
    { unitCode: "PDF", name: "Ruang Tunggu Pendaftaran", code: "RTP", description: "Area display dan antrian." },
    { unitCode: "FRM", name: "Ruang Farmasi", code: "RF", description: "Area pelayanan farmasi." },
    { unitCode: "FRM", name: "Gudang Farmasi", code: "GF", description: "Area penyimpanan farmasi." },
    { unitCode: "KSR", name: "Kasir Rawat Jalan", code: "KRJ", description: "Loket kasir rawat jalan." },
    { unitCode: "KSR", name: "Kasir Rawat Inap", code: "KRI", description: "Loket kasir rawat inap." },
    { unitCode: "LAB", name: "Ruang Sampling", code: "RS", description: "Area sampling dan label." },
    { unitCode: "LAB", name: "Ruang Analisis", code: "RA", description: "Area perangkat analisis." },
    { unitCode: "RAD", name: "Ruang Radiologi", code: "RR", description: "Area viewer radiologi." },
    { unitCode: "RAD", name: "Ruang Server Radiologi", code: "RSR", description: "Area perangkat pendukung radiologi." },
    { unitCode: "PAN", name: "Ruang Poli Anak", code: "RPA", description: "Ruang kerja poli anak." },
    { unitCode: "PAN", name: "Lobby Poli Anak", code: "LPA", description: "Area tunggu dan display poli anak." },
    { unitCode: "RIN", name: "Nurse Station", code: "NS", description: "Area kerja perawat rawat inap." },
    { unitCode: "RIN", name: "Koridor Rawat Inap", code: "KRI2", description: "Area koridor dan CCTV." },
    { unitCode: "IT", name: "Ruang IT", code: "RIT", description: "Area kerja IT Support." },
    { unitCode: "IT", name: "Ruang Server", code: "RSV", description: "Area server dan storage." },
    { unitCode: "IT", name: "Rack Jaringan", code: "RJ", description: "Area switch, router, dan firewall." },
    { unitCode: "IGD", name: "Nurse Station IGD", code: "NSI", description: "Area kerja IGD." },
    { unitCode: "IGD", name: "Triage", code: "TRG", description: "Area triage dan antrian IGD." },
    { unitCode: "RJ", name: "Lobby Rawat Jalan", code: "LRJ", description: "Area display informasi rawat jalan." },
    { unitCode: "RJ", name: "Counter Rawat Jalan", code: "CRJ", description: "Area counter rawat jalan." },
    { unitCode: "ADM", name: "Ruang Administrasi", code: "RADM", description: "Area administrasi umum." },
    { unitCode: "ADM", name: "Ruang Arsip", code: "ARS", description: "Area arsip operasional." },
    { unitCode: "KEU", name: "Ruang Keuangan", code: "RKEU", description: "Area kerja keuangan." },
    { unitCode: "KEU", name: "Ruang Klaim", code: "KLM", description: "Area administrasi klaim." },
    { unitCode: "HRD", name: "Ruang HRD", code: "RHRD", description: "Area kerja HRD." },
    { unitCode: "GUD", name: "Gudang Logistik", code: "GL", description: "Area penyimpanan logistik umum." },
    { unitCode: "MGT", name: "Ruang Direktur", code: "DIR", description: "Ruang kerja pimpinan." },
    { unitCode: "MGT", name: "Ruang Meeting", code: "MTG", description: "Ruang rapat manajemen." },
    { unitCode: "OK", name: "Ruang Operator", code: "ROP", description: "Area operator dan monitoring ruang operasi." },
    { unitCode: "OK", name: "Koridor OK", code: "KOK", description: "Area koridor ruang operasi." }
  ],
  categories: [
    { name: "Komputer", code: "CAT-01", description: "PC desktop operasional." },
    { name: "Laptop", code: "CAT-02", description: "Laptop kerja pengguna." },
    { name: "Printer", code: "CAT-03", description: "Printer dokumen dan label." },
    { name: "Scanner", code: "CAT-04", description: "Scanner dokumen." },
    { name: "Access Point", code: "CAT-05", description: "Perangkat Wi-Fi." },
    { name: "Switch", code: "CAT-06", description: "Switch jaringan." },
    { name: "UPS", code: "CAT-07", description: "Backup power perangkat IT." },
    { name: "CCTV", code: "CAT-08", description: "Kamera dan perangkat CCTV." },
    { name: "Server", code: "CAT-09", description: "Server aplikasi dan database." },
    { name: "Perangkat Antrian", code: "CAT-10", description: "Kiosk, display, dan controller antrian." },
    { name: "Router", code: "CAT-11", description: "Router dan gateway jaringan." },
    { name: "Firewall", code: "CAT-12", description: "Perangkat keamanan jaringan." },
    { name: "Storage NAS", code: "CAT-13", description: "Storage dan backup network attached." },
    { name: "Monitor", code: "CAT-14", description: "Monitor komputer dan display kerja." },
    { name: "Barcode Scanner", code: "CAT-15", description: "Scanner barcode operasional." },
    { name: "IP Phone", code: "CAT-16", description: "Telepon IP dan perangkat komunikasi." },
    { name: "Thin Client", code: "CAT-17", description: "Perangkat client ringan." },
    { name: "Periferal", code: "CAT-18", description: "Keyboard, mouse, webcam, dan perangkat pendukung." }
  ],
  brands: [
    { name: "Lenovo", description: "PC, laptop, dan kiosk." },
    { name: "HP", description: "PC, laptop, dan printer." },
    { name: "Dell", description: "Server, PC, dan monitor." },
    { name: "Acer", description: "PC dan laptop." },
    { name: "Asus", description: "Laptop dan perangkat pendukung." },
    { name: "Epson", description: "Printer dan scanner." },
    { name: "Canon", description: "Printer dan scanner." },
    { name: "Brother", description: "Printer label dan dokumen." },
    { name: "TP Link", description: "Access point dan router." },
    { name: "Cisco", description: "Switch dan perangkat jaringan." },
    { name: "MikroTik", description: "Router dan perangkat jaringan." },
    { name: "Ubiquiti", description: "Access point dan controller jaringan." },
    { name: "Fortinet", description: "Firewall dan keamanan jaringan." },
    { name: "APC", description: "UPS dan power protection." },
    { name: "Hikvision", description: "CCTV dan NVR." },
    { name: "Dahua", description: "CCTV dan NVR." },
    { name: "Synology", description: "NAS dan storage." },
    { name: "Zebra", description: "Barcode scanner dan printer label." }
  ],
  vendors: [
    { name: "Vendor Komputer Riau", contact: "PIC Komputer", phone: "0812-0000-0001", email: "komputer@example.local", address: "Pekanbaru" },
    { name: "Vendor Printer Riau", contact: "PIC Printer", phone: "0812-0000-0002", email: "printer@example.local", address: "Pekanbaru" },
    { name: "Vendor Jaringan Riau", contact: "PIC Jaringan", phone: "0812-0000-0003", email: "jaringan@example.local", address: "Pekanbaru" },
    { name: "Vendor Server Riau", contact: "PIC Server", phone: "0812-0000-0004", email: "server@example.local", address: "Pekanbaru" },
    { name: "Vendor Infrastruktur Riau", contact: "PIC Infrastruktur", phone: "0812-0000-0005", email: "infra@example.local", address: "Pekanbaru" },
    { name: "Vendor CCTV Riau", contact: "PIC CCTV", phone: "0812-0000-0006", email: "cctv@example.local", address: "Pekanbaru" },
    { name: "Vendor Antrian Riau", contact: "PIC Antrian", phone: "0812-0000-0007", email: "antrian@example.local", address: "Pekanbaru" },
    { name: "Vendor Maintenance IT", contact: "PIC Maintenance", phone: "0812-0000-0008", email: "maintenance@example.local", address: "Pekanbaru" },
    { name: "Vendor UPS dan Power", contact: "PIC Power", phone: "0812-0000-0009", email: "power@example.local", address: "Pekanbaru" },
    { name: "Vendor Barcode dan Label", contact: "PIC Barcode", phone: "0812-0000-0010", email: "barcode@example.local", address: "Pekanbaru" },
    { name: "Vendor Storage dan Backup", contact: "PIC Storage", phone: "0812-0000-0011", email: "storage@example.local", address: "Pekanbaru" },
    { name: "Vendor Firewall dan Security", contact: "PIC Security", phone: "0812-0000-0012", email: "security@example.local", address: "Pekanbaru" }
  ],
  technicians: [
    { name: "Budi Santoso", phone: "0812-1000-0001", specialty: "Komputer dan printer" },
    { name: "Rina Mahendra", phone: "0812-1000-0002", specialty: "Jaringan dan access point" },
    { name: "Fajar Pratama", phone: "0812-1000-0003", specialty: "Server dan backup" },
    { name: "Dewi Kartika", phone: "0812-1000-0004", specialty: "CCTV dan periferal" },
    { name: "Andi Saputra", phone: "0812-1000-0005", specialty: "UPS dan power" },
    { name: "Maya Lestari", phone: "0812-1000-0006", specialty: "Printer label dan scanner" },
    { name: "Hendra Wijaya", phone: "0812-1000-0007", specialty: "Firewall dan router" },
    { name: "Siti Nurhaliza", phone: "0812-1000-0008", specialty: "Aplikasi internal dan endpoint" }
  ]
} as const;
